apiVersion: apps/v1
kind: Deployment
metadata:
  name: qawety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qawety
  template:
    metadata:
      labels:
        app: qawety
    spec:
      containers:
      - image: okteto.dev/qawety:latest
        name: qawety
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4488d3a2-91ef-000e-7e02-ac5ec660ab1c"
        - name: Vless_Path
          value: "/vl5drsr55"
        - name: Vmess_UUID
          value: "4488d3a2-91ef-000e-7e02-ac5ec660ab1c"
        - name: Vmess_Path
          value: "/vm6uyd66"
        - name: Share_Path
          value: "/v2link"
